[colors]
background = "#ffffff"
foreground = "#1f2328"
cursor = "#0969da"
vi-cursor = "#8250df"
selection-background = "#1f2328"
selection-foreground = "#ffffff"

tabs = "#57606a"
tabs-active = "#1f2328"
bar = "#f6f8fa"
split = "#d0d7de"

black = "#24292f"
red = "#cf222e"
green = "#116329"
yellow = "#4d2d00"
blue = "#0969da"
magenta = "#8250df"
cyan = "#1b7c83"
white = "#6e7781"

light-black = "#57606a"
light-red = "#a40e26"
light-green = "#1a7f37"
light-yellow = "#633c01"
light-blue = "#218bff"
light-magenta = "#a475f9"
light-cyan = "#3192aa"
light-white = "#8c959f"
