[colors]
background = "#262335"
foreground = "#ffffff"
cursor = "#03edf9"
vi-cursor = "#ff7edb"
selection-background = "#ffffff20"
selection-foreground = "#ffffff"

tabs = "#848bbd"
tabs-active = "#ffffff"
bar = "#241b2f"
split = "#495495"

black = "#241b2f"
red = "#fe4450"
green = "#72f1b8"
yellow = "#f3e70f"
blue = "#03edf9"
magenta = "#ff7edb"
cyan = "#03edf9"
white = "#ffffff"

light-black = "#848bbd"
light-red = "#fe4450"
light-green = "#72f1b8"
light-yellow = "#fede5d"
light-blue = "#03edf9"
light-magenta = "#ff7edb"
light-cyan = "#03edf9"
light-white = "#ffffff"
